# -*- coding: utf-8 -*-
"""Trabalho DataWerehouses

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ldm1oAhot2nBkxqyb_447-xnc_LN6AzR
"""

import pandas as pan

# Autenticar conta Google
from google.colab import auth
auth.authenticate_user()

ds = pan.read_csv('https://raw.githubusercontent.com/AndreMorais77/Tabela_esporte/refs/heads/main/Tabela_Esportes.csv')

ds.columns = ds.columns.str.replace(' ', '_')
ds.columns = ds.columns.str.replace('(', '')
ds.columns = ds.columns.str.replace(')', '')

ds.dropna(how='any', inplace=True)
ds = ds.drop_duplicates()
ds.columns = ds.columns.str.replace('\n', '_')

ds.rename(columns={
    'Tabela_5_-_Escolas_públicas_estaduais_existentes_em_31.12_e_com_instalações_esportivas,': 'Grandes_Regiões_e_Unidades_da_Federação',
    'Unnamed:_1': 'TOTAL',
    'Unnamed:_2': 'Total_com_instalaçoes_esportivas',
    'Unnamed:_3': 'Somente_piscina',
    'Unnamed:_4': 'Somente_quadra_coberta',
    'Unnamed:_5': 'Somente_quadra_não-coberta'
}, inplace=True)

# encaminhando para BigQuery
from pandas_gbq import to_gbq

# Valores do projeto, dataset e tabela
project_id = 'trabalho-dw-458017'
dataset_table = 'trabalho_DW'
table_id = 'DW_esolaEsportiva'

destination_table = f"{dataset_table}.{table_id}"
to_gbq(ds, destination_table, project_id=project_id, if_exists='replace')